#!/usr/bin/env bash
# Scale NBA Stats Predictor backend instances
# Updates both docker-compose.override.yml and nginx.conf upstream block
# Usage: ./scripts/scale.sh <number_of_instances>
# Example: ./scripts/scale.sh 5

set -euo pipefail

MIN_INSTANCES=1
MAX_INSTANCES=8
COMPOSE_FILE="docker-compose.yml"

usage() {
    echo "Usage: $0 <number_of_instances>"
    echo ""
    echo "Scale the NBA Stats Predictor backend instances."
    echo "Accepts a number between ${MIN_INSTANCES} and ${MAX_INSTANCES}."
    echo ""
    echo "Examples:"
    echo "  $0 3    # Scale to 3 instances (default)"
    echo "  $0 5    # Scale to 5 instances"
    echo "  $0 1    # Scale to 1 instance (no load balancing)"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

INSTANCES="$1"

# Validate input is a number
if ! [[ "$INSTANCES" =~ ^[0-9]+$ ]]; then
    echo "Error: '$INSTANCES' is not a valid number."
    usage
fi

# Validate range
if [ "$INSTANCES" -lt "$MIN_INSTANCES" ] || [ "$INSTANCES" -gt "$MAX_INSTANCES" ]; then
    echo "Error: Instance count must be between ${MIN_INSTANCES} and ${MAX_INSTANCES}."
    exit 1
fi

# Verify Docker is available
if ! command -v docker &> /dev/null; then
    echo "Error: docker command not found. Please install Docker."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

if [ ! -f "${PROJECT_DIR}/${COMPOSE_FILE}" ]; then
    echo "Error: ${COMPOSE_FILE} not found in ${PROJECT_DIR}"
    exit 1
fi

NGINX_CONF="${PROJECT_DIR}/nginx/nginx.conf"
if [ ! -f "$NGINX_CONF" ]; then
    echo "Error: nginx.conf not found at ${NGINX_CONF}"
    exit 1
fi

echo "Scaling NBA Stats Predictor to ${INSTANCES} backend instance(s)..."
echo ""

# --- Step 1: Generate docker-compose.override.yml ---

OVERRIDE_FILE="${PROJECT_DIR}/docker-compose.override.yml"

{
    echo "# Auto-generated by scale.sh - do not edit manually"
    echo "# Generated for ${INSTANCES} instance(s)"
    echo "services:"
    echo "  nginx:"
    echo "    depends_on:"

    for i in $(seq 1 "$INSTANCES"); do
        echo "      nba-app-${i}:"
        echo "        condition: service_healthy"
    done

    echo ""

    for i in $(seq 1 "$INSTANCES"); do
        echo "  nba-app-${i}:"
        echo "    build: ."
        echo "    container_name: nba-app-${i}"
        echo "    restart: unless-stopped"
        echo "    expose:"
        echo "      - \"8501\""
        echo "    command: >"
        echo "      streamlit run app.py"
        echo "      --server.address=0.0.0.0"
        echo "      --server.port=8501"
        echo "      --browser.gatherUsageStats=false"
        echo "      --server.headless=true"
        echo "    networks:"
        echo "      - nba-network"
        echo "    healthcheck:"
        echo "      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8501/_stcore/health\"]"
        echo "      interval: 30s"
        echo "      timeout: 10s"
        echo "      retries: 3"
        echo "      start_period: 40s"
        echo ""
    done

    echo "networks:"
    echo "  nba-network:"
    echo "    driver: bridge"
} > "$OVERRIDE_FILE"

echo "Generated docker-compose.override.yml with ${INSTANCES} instances."

# --- Step 2: Update nginx.conf upstream block ---

# Build the new upstream server list
UPSTREAM_LINES=""
for i in $(seq 1 "$INSTANCES"); do
    UPSTREAM_LINES="${UPSTREAM_LINES}    server nba-app-${i}:8501 max_fails=3 fail_timeout=30s;"
    if [ "$i" -lt "$INSTANCES" ]; then
        UPSTREAM_LINES="${UPSTREAM_LINES}
"
    fi
done

# Back up the current nginx.conf
cp "$NGINX_CONF" "${NGINX_CONF}.bak"

# Replace the upstream block content between ip_hash and the closing brace
# Uses awk to precisely target the upstream block
awk -v servers="$UPSTREAM_LINES" '
    /^upstream nba_backends \{/ { in_upstream=1; print; next }
    in_upstream && /^\}/ {
        print "    ip_hash;"
        print ""
        print servers
        print "}"
        in_upstream=0
        next
    }
    in_upstream { next }
    { print }
' "$NGINX_CONF" > "${NGINX_CONF}.tmp"

# Verify the new config contains the expected servers
if ! grep -q "nba-app-${INSTANCES}:8501" "${NGINX_CONF}.tmp"; then
    echo "Error: Failed to update nginx.conf. Restoring backup."
    mv "${NGINX_CONF}.bak" "$NGINX_CONF"
    rm -f "${NGINX_CONF}.tmp"
    exit 1
fi

mv "${NGINX_CONF}.tmp" "$NGINX_CONF"
rm -f "${NGINX_CONF}.bak"

echo "Updated nginx.conf upstream block with ${INSTANCES} servers."
echo ""
echo "To apply changes, run:"
echo "  cd ${PROJECT_DIR}"
echo "  docker compose up -d --build"
echo ""
echo "To reload nginx without restarting (after config changes):"
echo "  ./scripts/reload_nginx.sh"
